//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLightViewer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataLightViewer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;Server&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;Database&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;&gt;
        ///          &lt;xs:complexType mixed=&quot;true&quot;&gt;
        ///            &lt;xs:sequence&gt;
        ///              &lt;xs:element name=&quot;Tables&quot; minOccurs=&quot;0&quot;&gt;
        ///                &lt;xs:complexType&gt;
        ///                  &lt;xs:sequence&gt;
        ///                    &lt;xs:element name=&quot;Table&quot; maxOcc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataToolsLight_Data {
            get {
                return ResourceManager.GetString("DataToolsLight_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;Server&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;Database&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;&gt;
        ///          &lt;xs:complexType mixed=&quot;true&quot;&gt;
        ///            &lt;xs:sequence&gt;
        ///              &lt;xs:element name=&quot;Tables&quot; minOccurs=&quot;0&quot;&gt;
        ///                &lt;xs:complexType&gt;
        ///                  &lt;xs:sequence&gt;
        ///                    &lt;xs:element name=&quot;Table&quot; maxOcc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataToolsLight_Data_Ext {
            get {
                return ResourceManager.GetString("DataToolsLight_Data_Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;Server&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;Database&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///            &lt;xs:sequence&gt;
        ///              &lt;xs:element name=&quot;DummyChild&quot; minOccurs=&quot;0&quot;&gt;
        ///                &lt;xs:complexType&gt;
        ///                  &lt;xs:simpleContent&gt;
        ///                    &lt;xs:extension base=&quot;xs:string&quot;&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataToolsLight_UI {
            get {
                return ResourceManager.GetString("DataToolsLight_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;Server&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;Database&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;&gt;	
        ///          &lt;xs:complexType&gt;
        ///            &lt;xs:sequence&gt;			  
        ///              &lt;xs:element name=&quot;Tables&quot; minOccurs=&quot;0&quot;&gt;
        ///                &lt;xs:complexType&gt;
        ///                  &lt;xs:sequence&gt;												  
        ///                    &lt;xs:element name=&quot;Table&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataToolsLight_UI_EXT {
            get {
                return ResourceManager.GetString("DataToolsLight_UI_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] t_sql_syntax {
            get {
                object obj = ResourceManager.GetObject("t_sql_syntax", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
