//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoaderTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoaderTest.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;NORTHWND&gt;
        ///  &lt;tables&gt;
        ///    &lt;table schemaName=&quot;dbo&quot; tableName=&quot;Orders&quot; object_id=&quot;21575115&quot; type=&quot;U &quot; type_desc=&quot;USER_TABLE&quot; create_date=&quot;12/13/2004 4:11:09 PM&quot; modify_date=&quot;12/13/2004 4:11:09 PM&quot;&gt;
        ///      &lt;columns&gt;
        ///        &lt;column name=&quot;OrderID&quot; type=&quot;int&quot; precision=&quot;10&quot; scale=&quot;0&quot; is_nullable=&quot;False&quot; is_identity=&quot;True&quot; maxLength=&quot;4&quot; /&gt;
        ///        &lt;column name=&quot;CustomerID&quot; type=&quot;nchar&quot; precision=&quot;0&quot; scale=&quot;0&quot; is_nullable=&quot;True&quot; is_identity=&quot;False&quot; maxLength=&quot;10&quot; /&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string db {
            get {
                return ResourceManager.GetString("db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string empty {
            get {
                return ResourceManager.GetString("empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;catalog&gt;
        ///   &lt;book id=&quot;bk101&quot;&gt;
        ///      &lt;author&gt;Gambardella, Matthew&lt;/author&gt;
        ///      &lt;title&gt;XML Developer&apos;s Guide&lt;/title&gt;
        ///      &lt;genre&gt;Computer&lt;/genre&gt;
        ///      &lt;price&gt;44.95&lt;/price&gt;
        ///      &lt;publish_date&gt;2000-10-01&lt;/publish_date&gt;
        ///      &lt;description&gt;An in-depth look at creating applications 
        ///      with XML.&lt;/description&gt;
        ///   &lt;/book&gt;
        ///   &lt;book id=&quot;bk102&quot; additionAttr=&quot;Hello&quot;&gt;
        ///      &lt;author&gt;Ralls, Kim&lt;/author&gt;
        ///      &lt;title&gt;Midnight Rain&lt;/title&gt;
        ///      &lt;genre&gt;Fantasy&lt;/genre&gt;
        ///      &lt;pric [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string in0 {
            get {
                return ResourceManager.GetString("in0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string out0 {
            get {
                return ResourceManager.GetString("out0", resourceCulture);
            }
        }
    }
}
